Fix mobile layout
spichka-media/website pull request #19
Opened 2024-04-23 12:41 UTC by ivan-spichka

https://www.notion.so/1f0d58ac149d462b86547c8d8d723310?pvs=4

видео в тикете

2024-04-26 06:23 UTC, spichkaJohn requested changes

2024-04-26 06:23 UTC, spichkaJohn commented on themes/spichka/resources/styles/app.scss
> +  word-break: break-word;
This can be replaced with `text-break` bootstrap class.

2024-04-26 06:23 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
>        </div>
`wp_is_mobile()`, потому что ресурс будет грузиться всё-равно.

2024-04-26 06:23 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
>            </a>
Ты скрыл кнопку доната навсегда ;]

2024-04-26 06:23 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
> +  <section class="mt-5 mb-5 ms-0 me-0 ps-1 connect">
Думаю, стоит переопределить переменные в bootstrap, а не добавлять ps-1 в нескольких местах.

2024-04-26 06:23 UTC, spichkaJohn commented on themes/spichka/resources/scripts/front-page.js
> +  sliders.forEach((container) => {
Эти стрелки занимают много места, и люди всё равно будут свайпать, а не клацать на них, я думаю, лучше реализовать как в, например, "Slides per view auto" https://swiperjs.com/demos где есть точки снизу для индикации, я соседняя карточка выглядывает, показывая, что есть куда скроллить.

Можно обсудить с дизайнером.

2024-04-26 06:23 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
> +  <section id="start" class="mt-3 ms-0 me-0 ps-1 program-articles">
Новые мерджены не соответствуют дизайну в фигме :(

2024-04-26 06:54 UTC, ivan-spichka commented on themes/spichka/resources/styles/app.scss
> +  word-break: break-word;
нет смысла разбивать этот стиль на два. Есть цельный стиль для использования в тексте. В бутстрапе нет дефисов, а они нужны

2024-04-26 06:56 UTC, ivan-spichka commented on themes/spichka/resources/scripts/front-page.js
> +  sliders.forEach((container) => {
эти стрелки как минимум подсказывают, что тут есть карусель и что можно свайпать. С дизайнером обсудить можно. Давай обсудим

2024-04-26 06:57 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +  <section id="start" class="mt-3 ms-0 me-0 ps-1 program-articles">
я не следовал дизайну, потому что дизайнер сказал, что дизайне не готов. Нет смысла сейчас реализовывать его, раз он не готов. Я сделал просто лучше, чем было, чтобы не совсем бросалось в глаза

2024-04-26 06:58 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +  <section class="mt-5 mb-5 ms-0 me-0 ps-1 connect">
о каких переменных ты говоришь?

2024-04-26 07:13 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +  <section id="start" class="mt-3 ms-0 me-0 ps-1 program-articles">
или фигма уже в том состоянии, что её целиком можно реализовывать?

2024-04-26 07:17 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
>            </a>
печаль, что-то глаз замылился и не заметил этого

2024-04-26 07:18 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +  <section class="mt-5 mb-5 ms-0 me-0 ps-1 connect">
здесь по-хорошему надо определить стиль secontion-gutters, определить нужные отступы внутри и вешать только этот стиль. А то полотно mt-5 mb-5 ms-0 me-0 ps-1 плохо выглядит

2024-04-26 07:25 UTC, ivan-spichka commented on themes/spichka/resources/scripts/front-page.js
> +  sliders.forEach((container) => {
в целом мне нравится, как выглядит slides per view auto, если там не возникнет проблем с несколькими отображением нескольких слайдов, то круто. А то некоторые модули у них отваливаются, если ставить на отображение одновременно 5 слайдов

2024-05-02 06:12 UTC, ivan-spichka commented on themes/spichka/resources/scripts/front-page.js
> +  sliders.forEach((container) => {
обновил свайпер на slidesPerView: 'auto'. Выглядит хорошо

2024-05-02 19:12 UTC, spichkaJohn requested changes

2024-05-02 19:12 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
> +  <section class="mt-5 mb-5 ms-0 me-0 ps-1 connect">
ms-0 me-0, как я понимаю, здесь лишние, вероятно, там нет отступов и так.

Лучше на контейнер повесить какой-то медиа запрос, который будет переопределять гаттеры на мобильном телефоне (--bs-gutter-x).

2024-05-04 17:00 UTC, spichkaJohn requested changes

2024-05-04 17:00 UTC, spichkaJohn commented on .husky/pre-commit
> +cd themes/spichka && yarn lint
<img width="385" alt="image" src="https://github.com/spichka-media/website/assets/145996884/21d4eb65-fb7a-4270-b098-56f7af97d247">

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/.stylelintrc.cjs
> +    'rule-empty-line-before': null
Я думаю это хорошое правило, почему оно удалено?

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/app.scss
> +}
Как-то это подозрительно.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/variables.scss
> +);
Нам действительно нужно столько размеров шрифтов, зачем? Думаю, стоит с дизайнером согласовать.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/.prettierrc
> +  "plugins": ["@prettier/plugin-php", "prettier-plugin-blade"],
Не забудь почистить vscode конфиги в этом ПРе. И лучше больше не смешивать несколько ПРов в один, чтобы легче было ревьювить.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
> +        </h1>
При семантической вёрстке не должно быть больше одного h1 на странице, наш сеошник будет возьмущён :)

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
> +        class="video-section flex-column text-white d-flex position-relative">
Баннер изменился, был в 3 строки, стал в две, размеры шрифтов изменились, этого не должно было произойти.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/footer.scss
> +  padding-bottom: $footer-vertical-padding;
Не думаешь, что 60 это многовато? Я вижу, что так в фигме, но что ты думаешь?

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/views/front-page.blade.php
> +                  <h3 class="card-title fw-semibold">
В фигме не semibold.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
>      }
Не уверен, что это хорошая идея, да и будет он один.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
> +      width: 70%;
Лучше верни колонку.

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
> +#front-page {
Может можно подключить этот стиль только на front-page чтобы не делать этот id?

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
> +    }
Как-то это запутанно, тебе не кажется?

2024-05-04 17:00 UTC, spichkaJohn commented on themes/spichka/resources/styles/app.scss
Разве договорились уже с дизайнером насчёт окончательной мобильной версии? Я видел в чате, что она собиралась подготовить что-то.

2024-05-04 17:25 UTC, spichkaJohn commented on .husky/pre-commit
> +cd themes/spichka && yarn lint
Разве в этом есть смысл, если prettier срабатывает при сохранении файла?

2024-05-04 18:45 UTC, ivan-spichka commented on themes/spichka/.stylelintrc.cjs
> +    'rule-empty-line-before': null
а я думаю, что это плохое правило) Можем это обсудить. Чем оно полезно?

2024-05-04 18:46 UTC, ivan-spichka commented on .husky/pre-commit
> +cd themes/spichka && yarn lint
может и нет, но хуже не будет. когда/если к нам подключится новый человек, то этот хук вынудит его настроить нормально приттиер локально. А то меня раздражало пушить и видеть упавший билд

2024-05-04 18:47 UTC, ivan-spichka commented on themes/spichka/resources/styles/variables.scss
> +);
это копи-паста кода бутстрапа с добавлением 7-го размера. Здесь на самом деле на один размер больше, но для того, чтобы мне переопределить $font-sizes пришлось каждый повторить

2024-05-04 18:48 UTC, ivan-spichka commented on themes/spichka/resources/styles/app.scss
> +}
поясни, не понимаю

2024-05-04 18:50 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
>      }
готов обсудить альтернативное предложение. Я считаю, что так норм, потому что этот селектор внутри другого лежит

2024-05-04 18:51 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +#front-page {
точно, это хорошая идея.

2024-05-04 18:51 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +      width: 70%;
размер такой, как в фигме. О подходе я не понял. Ты про подход с классами бутстрапа? Он тут неуместен

2024-05-04 18:53 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +    }
нет, мне не кажется, что это запутано. У нас не так много страниц и они все разные. Возможно, в дальнейшем станет ясно, как можно этот код сделать универсальным и переиспользовать, но сейчас это не очевидно

2024-05-04 18:55 UTC, ivan-spichka commented on themes/spichka/resources/styles/app.scss
я накидал хоть как-то чтобы не по уродски выглядело. Не претендую на то, что это финальная версия. Просто сделал, чтобы совсем уж глаз не кололо. Когда будет готов макет - допилю

2024-05-04 18:58 UTC, ivan-spichka commented on themes/spichka/.prettierrc
> +  "plugins": ["@prettier/plugin-php", "prettier-plugin-blade"],
спасибо, что напомнил о вскод конфигах. Можешь сориентировать, что в там нужно удалить? Выделенные строки?
![Uploading Screenshot 2024-05-04 at 21.57.24.png…]()

2024-05-05 04:26 UTC, spichkaJohn commented on themes/spichka/.prettierrc
> +  "plugins": ["@prettier/plugin-php", "prettier-plugin-blade"],
Да, и extension больше не нужен.

2024-05-05 04:29 UTC, spichkaJohn commented on themes/spichka/.stylelintrc.cjs
> +    'rule-empty-line-before': null
Как по мне, оно улучшает читабельность кода, добавляя расстояние между селекторами чтобы логические блоки визуально отделить.

2024-05-05 04:30 UTC, spichkaJohn commented on themes/spichka/resources/styles/app.scss
> +}
regular text это,  по смыслу, текст без стилей, сейчас у тебя это специальный стиль ещё и размером 6-ого заголовка, это попахивает.

2024-05-05 04:32 UTC, spichkaJohn commented on themes/spichka/resources/styles/variables.scss
> +);
Я так и не понял зачем ещё размеры, 6 это мало? Думаю, здесь что-то не так.

2024-05-05 04:34 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
> +      width: 70%;
В row должны быть только колонки, пожалуйста, убери этот width и верни колонку.

2024-05-05 04:36 UTC, spichkaJohn commented on themes/spichka/resources/styles/app.scss
Я к тому, что дизайна ещё нет, а уже несколько раз ревью этого ПРа и видимо, будет ещё, при этом дизайн не готов и снова переделывать, как-то это не очень, особенно если ты аппелируешь ко времени постоянно.

2024-05-05 04:38 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
>      }
Что не так было с прошлым вариантом? Там был текст нужного размера.

2024-05-05 04:40 UTC, spichkaJohn commented on themes/spichka/resources/styles/front-page.scss
> +    }
Почему хуже?

2024-05-05 05:02 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +    }
потому что эту штуку нужно копи-пастить каждую секцию. Сейчас есть одно место, которое определяет стили сразу для всех секций на странице, это оптимально

2024-05-05 05:02 UTC, ivan-spichka commented on themes/spichka/resources/styles/app.scss
я не понимаю, что ты предлагаешь? Я добавил буквально пару стилей, это было быстро. Мы дольше сейчас обсуждать их будем, чем я их добавлял

2024-05-05 05:03 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +      width: 70%;
тогда я уберу row. Предыдущие размеры не соответствуют дизайну, поэтому width останется в том или ином виде. Не вижу сейчас смысла копошиться в этих стилях

2024-05-05 05:05 UTC, ivan-spichka commented on themes/spichka/.stylelintrc.cjs
> +    'rule-empty-line-before': null
на мой взгляд оно растягивает размер файла и увеличивает расстояние, которое нужно пройти глазам до следующего правила. Это не критично, когда правил два, но когда правил много файл необоснованно раздувается

2024-05-05 05:07 UTC, ivan-spichka commented on themes/spichka/resources/styles/footer.scss
> +  padding-bottom: $footer-vertical-padding;
более-менее, мб слегка многовато. Мне в целом вначале не нравились большие отступы в фигме, но сейчас кажется, что и неплохо. Если будем исправлять, то в отдельном пре с пачкой аналогичных мелких изменений, которые наверняка будут

2024-05-05 05:12 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +        </h1>
не будет)

https://webdesign.tutsplus.com/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824a
https://ru.hexlet.io/blog/posts/koe-chto-pro-h1-na-odnoy-stranitse

2024-05-05 05:13 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +        class="video-section flex-column text-white d-flex position-relative">
да, так и задумано. Было неправильно, стало правильно - как в фигме

2024-05-05 05:14 UTC, ivan-spichka commented on themes/spichka/resources/styles/variables.scss
> +);
6 это не мало, но среди этих 6-ти нет нужного. Мне нужен было зафиксировать в наших переменных размер текста в 1.125rem - 18px для дальнейшего переиспользования. Такой размер по умолчанию отсутствует в бутстрапе.

2024-05-05 05:17 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
>      }
раньше текст был размером в 48px, теперь в 50px - как в фигме дизайнер разработал

2024-05-05 05:20 UTC, ivan-spichka commented on themes/spichka/resources/styles/app.scss
> +}
regular-text это не текст без стилей, это стандартный текст на нашем сайте, как он должен отображаться в обычной ситуации. Размер 6го заголовка у него потому, что мапка font-sizes перечисляет размеры шрифтов и использует там заголовки. Это норм выглядит. Ну или как минимум не настолько плохо, чтобы сейчас с этим что-то делать, потому как не очевидны минусы этого

2024-05-05 05:22 UTC, ivan-spichka commented on themes/spichka/resources/views/front-page.blade.php
> +                  <h3 class="card-title fw-semibold">
слова в фигме не ложатся на слова в бутстрапе. Я нашел плюс-минус схожее значение и поставил его сюда. Если здесь поставить слово, как в фигме, то будет слишком жирно.

2024-05-05 05:47 UTC, ivan-spichka commented on themes/spichka/resources/styles/app.scss
> +}
ну и доп. аргумент: никогда, сколько работал, не видел ничего подобного на проектах

2024-05-05 05:48 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +      width: 70%;
в целом, фронтендеры обычно не уделяют столько внимания вёрстке. Отображается как надо и код выглядит норм - отлично

2024-05-05 05:51 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +#front-page {
подумал еще об этой идее. Всё-таки не совсем она хорошая. Подключить стили front-page только для front-page - это хорошая идея. А вот убирать айдишник - плохая, потому что тогда нам сложнее будет читать и скоупить стили. Будет выше риск пересечения разных стилей. Обычно стили при объявлении скоупят, чтобы ограничить область применения

2024-05-05 18:11 UTC, ivan-spichka commented on themes/spichka/resources/styles/front-page.scss
> +#front-page {
за 15 минут не получилось нормально подключить отдельный scss файл к нужной странице. отложу это на потом

2024-05-05 18:12 UTC, ivan-spichka commented on themes/spichka/.prettierrc
> +  "plugins": ["@prettier/plugin-php", "prettier-plugin-blade"],
убрал

2024-05-05 18:15 UTC, merged