chore: post header box UI
spichka-media/website pull request #20
Opened 2024-04-25 06:55 UTC by ivan-spichka

2024-04-26 05:34 UTC, spichkaJohn commented
Постарайся сделать как в figma 
<img width="676" alt="image" src="https://github.com/spichka-media/website/assets/145996884/85e6dc48-a13e-4b84-8e2d-a281cd24b5f7">

2024-04-26 05:54 UTC, spichkaJohn requested changes

2024-04-26 05:54 UTC, spichkaJohn commented on themes/spichka/resources/styles/single-post.scss
> +    }
Есть проблема, если несколько меток

<img width="689" alt="image" src="https://github.com/spichka-media/website/assets/145996884/5b661be3-101b-4e13-bef5-478e4e745b63">

2024-04-26 05:54 UTC, spichkaJohn commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +              <span>{{ _e('Categories') }}:</span><span class="ms-1">@php(the_category(', '))</span>
Нужно ли заворачивать Categories в span?

2024-04-26 05:54 UTC, spichkaJohn commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +        <div class="d-flex flex-column">
Что изменится, если убрать классы у этого div?

2024-04-26 05:54 UTC, spichkaJohn commented on themes/spichka/resources/styles/single-post.scss
Постарайся сделать как в figma https://www.figma.com/file/Qa7TrJ7PN5C6O59qE4KDn9/%F0%9F%94%A5-spichka.media?type=design&node-id=116-850&mode=design&t=VrwYbf2eNAnXIHea-4

2024-04-26 06:35 UTC, ivan-spichka commented on themes/spichka/resources/styles/single-post.scss
> +    }
точняк, что-то я попутал. Подумал, что это иконка

2024-04-26 06:43 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +              <span>{{ _e('Categories') }}:</span><span class="ms-1">@php(the_category(', '))</span>
текст лучше всегда оборачивать, т.к. текст в спане и текс в div несколько по-разному отображаются. Конкретно здесь я обернул categories, т.к. обернул текст справа от него и решил сделать одинаково для двоих

2024-04-26 07:02 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +        <div class="d-flex flex-column">
я тут проверил: ничего не изменится даже если убрать этот див)

2024-04-26 07:09 UTC, ivan-spichka commented on themes/spichka/resources/styles/single-post.scss
ок

2024-05-01 18:25 UTC, ivan-spichka commented on themes/spichka/resources/styles/single-post.scss
> +    }
сделал классом

2024-05-01 18:25 UTC, ivan-spichka commented on themes/spichka/resources/styles/single-post.scss
> +    }
исправил

2024-05-01 18:25 UTC, ivan-spichka commented on themes/spichka/resources/styles/single-post.scss
> +    }
но нужна будет помощь с получением слова "Метки:". Хз, как это организовать правильно. По идее тащить из темы надо

2024-05-01 18:26 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +        <div class="d-flex flex-column">
а вот теперь он таки нужен

2024-05-01 18:26 UTC, ivan-spichka commented on themes/spichka/resources/styles/single-post.scss
сделал

2024-05-02 18:15 UTC, spichkaJohn requested changes

2024-05-02 18:15 UTC, spichkaJohn commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +      <div class="col-sm-6 d-flex flex-column row-gap-4 gx-6">
Нет такого класса, как gx-6

2024-05-02 18:15 UTC, spichkaJohn commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +      <div class="col-sm-6 gx-6">
Нет gx-6.

2024-05-02 18:15 UTC, spichkaJohn commented on themes/spichka/resources/styles/single-post.scss
Не похоже :( Расстояния слева/снизуот заголовка статьи, жирность, размер текста меток не соответствуют, перепроверь всё ещё раз, пожалуйста.

2024-05-02 18:29 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +              <div>Метки:</div>
о, спасибо

2024-05-02 18:30 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +        <div class="d-flex flex-column row-gap-3">
давай так замержим, потом сделаем фикс по фигме. там наверняка что-то еще появится

2024-05-02 18:33 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +      <div class="col-sm-6 d-flex flex-column row-gap-4 gx-6">
да, точно. забавно)

2024-05-02 18:33 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +              <div>@php(the_tags('', ', '))</div>
тут не подходит по семантике для тегов. спан это блок текста, а @php(the_tags('', ', ')) возвращает набор элементов <a>. А вот для текста "метки:" мб и можно

2024-05-03 07:16 UTC, spichkaJohn commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +              <div>@php(the_tags('', ', '))</div>
Что в "Рубрики", что в "Авторы", там span и такой же набор элементов, думаю, стоит одного стиля придерживаться.

2024-05-04 16:22 UTC, ivan-spichka commented on themes/spichka/resources/views/partials/content-single-post.blade.php
> +              <div>@php(the_tags('', ', '))</div>
это совсем не критично

2024-05-22 06:43 UTC, merged