add-site-kit
spichka-media/website pull request #4
Opened 2024-04-05 14:30 UTC by ivan-spichka

2024-04-05 15:42 UTC, spichkaJohn requested changes

2024-04-05 15:42 UTC, spichkaJohn commented on themes/spichka/functions.php
> +            'force_activation' => true
Я думаю не стоит его делать required и force, и без него шаблон будет работать.

2024-04-06 08:26 UTC, ivan-spichka commented on themes/spichka/functions.php
> +            'force_activation' => true
поправил

2024-04-06 15:20 UTC, spichkaJohn submitted a review, later dismissed

2024-04-08 07:38 UTC, closed without merging