Add main portraits logic
spichka-media/website pull request #52
Opened 2024-12-15 13:09 UTC by GalenMad

- Добавлен модуль ReservoirRandomizer;
- Добавлен модуль контроллеров для хедлайнеров;
- Добавлен модуль с поддержкой ручки `/wp-json/custom-fields/theme_options`;
- Добавлен модуль с наблюдателем для отложенной загрузки хедлайнеров;
- Добавлена логика показа тултипов и смены портретов в зависимости от типа устройства;
- Добавлены стили для тултипа;
- Немного изменён шаблон футера.

2024-12-15 17:27 UTC, spichkaJohn requested changes

2024-12-15 17:27 UTC, spichkaJohn commented on themes/spichka/resources/scripts/lib/portraits/index.js
> +
Думаю на ховере должен показываться тултип и меняться лицо и при mouseleave возвращаться в исходное состояние.

2024-12-15 17:27 UTC, spichkaJohn commented on themes/spichka/resources/scripts/lib/portraits/index.js
> +        }
Стоит завтра логику обсудить ещё раз.

2024-12-15 20:29 UTC, GalenMad commented on themes/spichka/resources/views/sections/footer.blade.php
> +        {!! wp_get_attachment_image(carbon_get_theme_option('theme_footer_image'), [95, 120], false, ['id' => 'theme-main-footer-image']) !!}
С другими размерам необъяснимо багует подгрузка картинки, так что да, пока убрал. 

Но размеры 95 на 120 по макетам сделаны.

2024-12-15 20:34 UTC, GalenMad commented on themes/spichka/resources/views/sections/footer.blade.php
> +<footer class="py-9 bg-light" id="theme-main-footer">
Не соглашусь. Спека допускает использование нескольких таких тегов на странице, а потом забыть, что у тебя на этот тег завязана какая-то логика довольно легко. 

Предлагаю хоть что-то уникальное оставить, хотя бы класс какой-нибудь, если id не нравится.

2024-12-15 20:35 UTC, GalenMad commented on themes/spichka/resources/views/sections/footer.blade.php
> +      <article
Довольно спорное утверждение. Но если для тебя есть разница — ок, верну див, мне не принципиально.

2024-12-15 20:36 UTC, GalenMad commented on themes/spichka/resources/styles/app.scss
> +    height: 15px;
Так портреты же в пикселях?

2024-12-15 20:37 UTC, GalenMad commented on themes/spichka/resources/styles/variables.scss
> +$light-gray: #dadada;
Для стрелки от тултипа отдельную переменную?

2024-12-15 20:39 UTC, GalenMad commented on themes/spichka/resources/scripts/lib/portraits/observer.js
> +export const initDisposableIntersectionObserver = (callback, targetElement, topDistance = 200) => {
Вроде не увидел нигде такого ограничения, предлагаю на уровне линтера зафиксировать сразу.

2024-12-15 20:40 UTC, GalenMad commented on themes/spichka/resources/scripts/lib/portraits/randomizer.js
> +export function createReservoirRandomizer(length, exceptIndex = null) {
Не понял, типа декартово произведение цитат и портретов?

2024-12-15 20:43 UTC, GalenMad commented on themes/spichka/resources/styles/app.scss
> +  position: relative;
Ты про габариты тултипа? Тогда давай договоримся в каком файле будем это делать, чтобы кто-то другой потом не полез переопределять.

2024-12-15 20:46 UTC, GalenMad commented on themes/spichka/resources/scripts/lib/portraits/index.js
> +         || 'ontouchstart' in window;
Да, про hover: none не подумал. Согласен, что нужно его использовать.

Но про константу не понял. Зачем каждый раз дёргать?

2024-12-15 20:48 UTC, GalenMad commented on themes/spichka/resources/scripts/lib/portraits/index.js
> +
Надо будет в понедельник ТЗ ещё раз проговорить)

2024-12-15 21:12 UTC, spichkaJohn commented on themes/spichka/resources/scripts/lib/portraits/observer.js
> +export const initDisposableIntersectionObserver = (callback, targetElement, topDistance = 200) => {
Хорошо, я расширю линтер.

2024-12-15 21:21 UTC, spichkaJohn commented on themes/spichka/resources/styles/variables.scss
> +$light-gray: #dadada;
Или просто переопределить переменную бутстрапа, раньше можно было у стрелки.

Вижу в фигме у тултипа и стрелки разный цвет, лучше у дизайнера уточни ожидаемо ли это.

2024-12-15 21:23 UTC, spichkaJohn commented on themes/spichka/resources/views/sections/footer.blade.php
> +<footer class="py-9 bg-light" id="theme-main-footer">
Хорошо, пусть будет id.

2024-12-15 21:23 UTC, spichkaJohn commented on themes/spichka/resources/scripts/lib/portraits/observer.js
> +export const initDisposableIntersectionObserver = (callback, targetElement, topDistance = 200) => {
Расширил.

2024-12-15 21:24 UTC, spichkaJohn commented on themes/spichka/resources/scripts/lib/portraits/randomizer.js
> +export function createReservoirRandomizer(length, exceptIndex = null) {
Да, завтра обсудим.

2024-12-16 20:02 UTC, spichkaJohn commented on themes/spichka/resources/scripts/lib/portraits/index.js
> +        }
Не стоит в DOM хранить

headlinersPortraitElement.setAttribute('data-state', 'hover');

2024-12-17 01:12 UTC, closed without merging